# Generated by Django 3.1.4 on 2020-12-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201228_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
