# Generated by Django 3.0.8 on 2020-12-20 07:09

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201219_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default_profile_pic2.png', upload_to=users.models.upload_location),
        ),
    ]
