# Generated by Django 3.0.8 on 2020-12-18 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import questions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, unique=True)),
                ('content', models.TextField(blank=True, max_length=300, null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='QuestionsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='What is the title of your question?', max_length=100, unique=True, verbose_name='Title')),
                ('content', models.TextField(max_length=3000)),
                ('slug', models.SlugField(unique=True)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('image', models.ImageField(blank=True, null=True, upload_to=questions.models.upload_location)),
                ('shares', models.IntegerField()),
                ('answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='answers.AnswersModel')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_author', to=settings.AUTH_USER_MODEL)),
                ('q_tags', models.ManyToManyField(to='questions.Tags')),
                ('vote_down', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_down', to=settings.AUTH_USER_MODEL)),
                ('vote_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_up', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
