# Generated by Django 3.0.8 on 2020-12-18 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_auto_20201218_0420'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsmodel',
            name='answers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='answers.AnswersModel'),
        ),
        migrations.AlterField(
            model_name='questionsmodel',
            name='q_tags',
            field=models.ManyToManyField(blank=True, null=True, to='questions.Tags'),
        ),
        migrations.AlterField(
            model_name='questionsmodel',
            name='shares',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='questionsmodel',
            name='vote_down',
        ),
        migrations.AddField(
            model_name='questionsmodel',
            name='vote_down',
            field=models.ManyToManyField(blank=True, null=True, related_name='vote_down', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='questionsmodel',
            name='vote_up',
        ),
        migrations.AddField(
            model_name='questionsmodel',
            name='vote_up',
            field=models.ManyToManyField(blank=True, null=True, related_name='vote_up', to=settings.AUTH_USER_MODEL),
        ),
    ]
