# Generated by Django 3.0.8 on 2020-12-18 10:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0002_auto_20201218_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='content',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='slug',
        ),
        migrations.AddField(
            model_name='tags',
            name='description',
            field=models.TextField(blank=True, help_text='You can optionally provide a description for this tag', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='questionsmodel',
            name='q_tags',
            field=models.ManyToManyField(blank=True, to='questions.Tags'),
        ),
        migrations.AlterField(
            model_name='questionsmodel',
            name='vote_down',
            field=models.ManyToManyField(blank=True, related_name='vote_down', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionsmodel',
            name='vote_up',
            field=models.ManyToManyField(blank=True, related_name='vote_up', to=settings.AUTH_USER_MODEL),
        ),
    ]
