# Generated by Django 3.0.8 on 2020-12-19 01:46

from django.db import migrations, models
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20201218_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsmodel',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='questionsmodel',
            name='content',
        ),
        migrations.AlterField(
            model_name='questionsmodel',
            name='image',
            field=models.ImageField(blank=True, help_text='Add image (optional)', null=True, upload_to=questions.models.upload_location),
        ),
        migrations.AlterField(
            model_name='questionsmodel',
            name='title',
            field=models.CharField(help_text='What is the title of your question?', max_length=65, unique=True, verbose_name='Title'),
        ),
    ]
