# Generated by Django 3.1.4 on 2020-12-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20201219_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsmodel',
            name='title',
            field=models.CharField(help_text='What is the title of your question?', max_length=265, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
