# Generated by Django 3.0.8 on 2020-12-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersmodel',
            name='content',
            field=models.TextField(max_length=3000),
        ),
    ]
