# Generated by Django 3.0.8 on 2020-12-19 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20201219_0246'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('answers', '0002_auto_20201218_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersmodel',
            name='likes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answersmodel',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='questions.QuestionsModel'),
        ),
        migrations.AlterField(
            model_name='answersmodel',
            name='send_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answersmodel',
            name='shares',
            field=models.IntegerField(default=0),
        ),
    ]
