# Generated by Django 3.1.4 on 2020-12-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_auto_20201219_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersmodel',
            name='content',
            field=models.TextField(max_length=555),
        ),
    ]
