# Generated by Django 3.1.4 on 2021-01-17 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cheaters', '0001_initial'),
        ('gossips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FalseInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=255)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('cheater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='false_cheater', to='cheaters.cheatersmodel')),
                ('gossip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='false_gossip', to='gossips.gossipsmodel')),
            ],
        ),
    ]
