# Generated by Django 3.0.8 on 2020-12-19 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gossips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gossipsmodel',
            options={'verbose_name_plural': 'Gossips'},
        ),
        migrations.RemoveField(
            model_name='gossipsmodel',
            name='false',
        ),
        migrations.AddField(
            model_name='gossipsmodel',
            name='false',
            field=models.ManyToManyField(blank=True, null=True, related_name='false', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='gossipsmodel',
            name='true',
        ),
        migrations.AddField(
            model_name='gossipsmodel',
            name='true',
            field=models.ManyToManyField(blank=True, null=True, related_name='true', to=settings.AUTH_USER_MODEL),
        ),
    ]
