# Generated by Django 3.0.8 on 2020-12-19 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gossips', '0002_auto_20201219_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gossipsmodel',
            name='false',
            field=models.ManyToManyField(blank=True, related_name='false', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gossipsmodel',
            name='true',
            field=models.ManyToManyField(blank=True, related_name='true', to=settings.AUTH_USER_MODEL),
        ),
    ]
