# Generated by Django 3.1.4 on 2020-12-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gossips', '0003_auto_20201219_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gossipsmodel',
            name='title',
            field=models.CharField(help_text='What is the title of your gossip?', max_length=255, unique=True, verbose_name='Title'),
        ),
    ]
