# Generated by Django 3.0.8 on 2020-12-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheaters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheatersmodel',
            name='title',
            field=models.CharField(help_text='What is the title of your cheater story?', max_length=75, unique=True, verbose_name='Title'),
        ),
    ]
