# Generated by Django 3.1.4 on 2020-12-29 09:28

import cheaters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheaters', '0002_auto_20201228_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheatersmodel',
            name='image',
            field=models.ImageField(default='', help_text='Add image (Mandatory)', upload_to=cheaters.models.upload_location),
        ),
    ]
